version: "3"

services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: glml-postgres
      POSTGRES_DB: glml
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database:/docker-entrypoint-initdb.d
